server:
  port: 8000

  ssl:
    key-store-password: b302capsule
    key-store: classpath:keystore.p12
    key-store-type: PKCS12

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://k8b302.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/member/**
          filters:
            - AuthorizationHeaderFilter

        - id: outh-service
          uri: lb://OUTH-SERVICE
          predicates:
            - Path=/api/aouth/**

        - id: capsule-service
          uri: lb://CAPSULE-SERVICE
          predicates:
            - Path=/api/capsule/**
          filters:
            - AuthorizationHeaderFilter

        - id: chat
          uri: lb://CHAT
          predicates:
            - Path=/api/chat/**
          filters:
            - AuthorizationHeaderFilter

token:
  secret: YWJvdXQtdGltZS1jYXBzdWxlLWFib3V0LXRpbWUtY2Fwc3VsZS1hYm91dC10aW1lLWNhcHN1bGUtYWJvdXQtdGltZS1jYXBzdWxl
