server:
  port: 8000

  ssl:
    key-store-password: b302capsule
    key-store: classpath:keystore.p12
    key-store-type: PKCS12

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://k8b302.p.ssafy.io:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER
          predicates:
            - Path=/api/member/**
        - id: outh-service
          uri: lb://OUTH
          predicates:
            - Path=/api/aouth/**
        - id: capsule-service
          uri: lb://CAPSULE
          predicates:
            - Path=/api/capsule/**
        - id: chat-service
          uri: lb://CHAT
          predicates:
            - Path=/api/chat/**

token:
  secret: YWJvdXQtdGltZS1jYXBzdWxlLWFib3V0LXRpbWUtY2Fwc3VsZS1hYm91dC10aW1lLWNhcHN1bGUtYWJvdXQtdGltZS1jYXBzdWxl
