server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: outh-service
  redis:
    host: localhost
    port: 6379
  datasource:
      url: ENC(KaOl4PVIKbGwb9QY3nUNzTuR7DXv4kH2qxldE9E/3lZAcP7sIfuz9JRJnBT5ORNd0FQ7mAxhhmlU3XqSkY53/4rd1ha2tPYUElIV0j9nr1smy/x1zzT1drEg2xYPRNvoCQDOsmeMPaZqtDcOfkjw98HFTb/xgKIDCwg85mgqRmCXKgKI17uX+FFnRPoZN0uDdZNW2k5p/+62TprQUz4Qp6bJQl4Ez+4Evoc8yFEDoU6ayRqqmslewQ==)
      username: ENC(OKeWGkiqftrwASd9hdvTVw==)
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: ENC(zOFLXE2MDlGqH25weLzgQg==)
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
        format_sql: true
        check_nullability: true
  profiles:
    include: oauth

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret-key: ENC(A8+SVnn87vjKG/4udGeW0wpGZaYPay993ScsasGAMtK/M9HezBDAPWA5aQOL2pCoYFomu96hGsaFaZMUHKKeI94aJgfZw3kboui4OvS+2Bckcxt7eaDotjoG9OzQ0LKH0pl+b+sbCFHGcND49/KEXg==)
  refresh-expiration-time: 1209600 # 14일
  access-expiration-time: 43200 # 12시간

