# 스프링 시큐리티를 사용하고 있다면 아래와 같이 설정 파일에 적어준 정보들로 애플리케이션 실행 시 Oauth2ClientProperties 객체를 생성함
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: _m8nkPSevg4N3fGEiDgq
            client-secret: CacOwjb4ma
            authorization-grant-type: authorization_code
#            redirect-uri: "https://localhost:9002/api/oauth/naver/callback"
            redirect-uri: "https://k8b302.p.ssafy.io/api/oauth/naver/callback"
            scope:
              - email
              - profile_image
            client-name: naver
          kakao:
            client-id: 344aa8ae1b69c829e695e47c8a7beb1e
#            redirect-uri: "https://localhost:9002/api/oauth/kakao/callback"
            redirect-uri: "https://k8b302.p.ssafy.io/api/oauth/kakao/callback"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - account_email
            client-secret : EnB1DzXuZuP5WrcraVKtpbtixBaxXj0w
            client-name: kakao
        # Spring security에서 제공하는 oauth2-client 라이브러리에는 유명한 google, facebook, twitter 등 웹사이트에 대한 Provider들은 제공을 한다.
        # 하지만 우리나라에서만 한정적으로 사용하는 네이버나, 카카오 같은 서비스에 대한 정보들을 제공해주지 못한다.
        # 따라서 Spring Security에서 제공하지 않는 Provider의 oauth2를 사용하기 위한 설정을 해야 한다.
        # CommonOAuth2Provider에서 해주던 값들을 application-oauth.yml 파일에 모두 수동으로 입력한다.
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버가 회원정보를 json으로 넘겨주는데, response라는 키값으로 리턴해준다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오가 회원정보를 json으로 넘겨주는데, id라는 키값으로 리턴해준다.