server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      enable: true
      force: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: capsule-service

  datasource:
    # local
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abouttimecapsule?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: ssafy
    password: ssafy

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
        format_sql: true
        check_nullability: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher